# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norwegian_name', models.CharField(max_length=255, verbose_name='Norwegian Name')),
                ('short_name', models.CharField(max_length=50, verbose_name='Short name')),
                ('code', models.CharField(max_length=15, verbose_name='Code')),
                ('faculty_code', models.IntegerField(default=0, verbose_name='Faculty Code')),
                ('english_name', models.CharField(max_length=255, verbose_name='English name')),
                ('credit', models.FloatField(default=7.5, verbose_name='Credit')),
                ('study_level', models.SmallIntegerField()),
                ('taught_in_spring', models.BooleanField(default=False)),
                ('taught_in_autumn', models.BooleanField(default=False)),
                ('taught_from', models.IntegerField()),
                ('taught_in_english', models.BooleanField(default=False)),
                ('last_year_taught', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('learning_form', models.TextField()),
                ('learning_goal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_code', models.CharField(max_length=10, verbose_name='Semester')),
                ('average_grade', models.FloatField()),
                ('passed', models.IntegerField(default=0)),
                ('a', models.SmallIntegerField(default=0)),
                ('b', models.SmallIntegerField(default=0)),
                ('c', models.SmallIntegerField(default=0)),
                ('d', models.SmallIntegerField(default=0)),
                ('e', models.SmallIntegerField(default=0)),
                ('f', models.SmallIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32, verbose_name='Tag text')),
                ('courses', models.ManyToManyField(to='grades.Course')),
            ],
        ),
    ]
