# Generated by Django 3.0 on 2020-02-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_grade_digital_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_type',
            field=models.CharField(default='', max_length=255, verbose_name='Exam Type'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade_type',
            field=models.CharField(default='', max_length=255, verbose_name='Grade Type'),
        ),
        migrations.AddField(
            model_name='course',
            name='have_had_digital_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.CharField(default='', max_length=255, verbose_name='Place'),
        ),
    ]
