# Generated by Django 3.0 on 2020-05-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_auto_20200217_2316"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.IntegerField(
                        help_text="Nøkkel fra Karstat",
                        unique=True,
                        verbose_name="Nøkkel",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Navn", null=True),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=32, verbose_name="Forkortelse", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Fakultet",
                "verbose_name_plural": "Fakulteter",
                "ordering": ("key",),
            },
        ),
    ]
