# Generated by Django 3.0 on 2020-05-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_auto_20200512_1057"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="have_had_digital_exam",
            new_name="has_had_digital_exam",
        ),
    ]
