# Generated by Django 3.0 on 2020-05-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0005_auto_20200512_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="attendee_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course", name="average", field=models.FloatField(default=0),
        ),
    ]
