# Generated by Django 3.0 on 2020-05-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0009_auto_20200514_1432"),
    ]

    operations = [
        migrations.RemoveField(model_name="tag", name="courses",),
    ]
