# Generated by Django 3.0 on 2020-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0010_remove_tag_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="courses",
            field=models.ManyToManyField(
                related_name="tags", through="grades.CourseTag", to="grades.Course"
            ),
        ),
    ]
