# Generated by Django 3.0 on 2020-05-14 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("grades", "0011_tag_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetag",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
