# Generated by Django 3.0 on 2020-05-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0006_department"),
        ("grades", "0012_coursetag_created_by"),
    ]

    operations = []
