# Generated by Django 3.0 on 2020-05-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0014_auto_20200515_1440"),
    ]

    operations = [
        migrations.DeleteModel(name="Department",),
        migrations.DeleteModel(name="Faculty",),
    ]
