# Generated by Django 3.0 on 2020-05-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0016_department_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="grades.Faculty",
            ),
        ),
    ]
