# Generated by Django 3.0 on 2020-05-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0017_auto_20200515_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="english_name",
            field=models.CharField(
                default="", max_length=256, verbose_name="Engelsk navn"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="english_name",
            field=models.CharField(
                default="", max_length=256, verbose_name="Engelsk navn"
            ),
        ),
    ]
