# Generated by Django 3.0 on 2020-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0019_auto_20200516_0642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="taught_from",
            field=models.IntegerField(default=0),
        ),
    ]
