# Generated by Django 3.0 on 2020-05-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0020_auto_20200516_0711"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grade", unique_together={("course", "semester_code")},
        ),
    ]
