# Generated by Django 3.0 on 2020-05-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0021_auto_20200516_0953"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="grades.Department",
            ),
        ),
    ]
