# Generated by Django 3.0 on 2020-05-17 12:48

from django.db import migrations


def split_semester_code(apps, schema_editor):
    Grade = apps.get_model("grades", "Grade")
    for index, grade in enumerate(Grade.objects.all()):
        semester_code = grade.semester_code
        semester_letter, year = semester_code[0], int(semester_code[1:5])
        lookup = {"V": "SPRING", "S": "SUMMER", "H": "AUTUMN"}
        grade.semester, grade.year = lookup[semester_letter], year
        grade.save()


def merge_semester_code(apps, schema_editor):
    Grade = apps.get_model("grades", "Grade")
    for grade in Grade.objects.all():
        lookup = {"SPRING": "V", "SUMMER": "S", "AUTUMN": "H"}
        semester_code = f"{lookup[grade.semester]}{grade.year}"
        grade.semester_code = semester_code
        grade.save()


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0023_auto_20200517_1248"),
    ]

    operations = [
        migrations.RunPython(split_semester_code, merge_semester_code),
    ]
