# Generated by Django 3.0 on 2020-05-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0024_auto_20200517_1248"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="grade", unique_together={("course", "semester", "year")},
        ),
    ]
