# Generated by Django 3.0 on 2020-05-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0025_auto_20200517_1351"),
    ]

    operations = [
        migrations.RemoveField(model_name="grade", name="semester_code",),
    ]
