name: Publish to registry
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gradestats
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.online.ntnu.no
          workdir: .
          tag_names: true
